//! Classify built-in test semantics from the checked compiler context.
use std::collections::BTreeMap;

use rustc_hir::def::DefKind;
use rustc_hir::def_id::LocalDefId;
use rustc_middle::ty::{self, TyCtxt};

pub struct Index<'tcx> {
    tcx: TyCtxt<'tcx>,
    builtin: bool,
    descriptors: BTreeMap<String, Vec<LocalDefId>>,
    functions: Vec<(String, String, LocalDefId)>,
}

impl<'tcx> Index<'tcx> {
    pub fn new(tcx: TyCtxt<'tcx>) -> Self {
        let builtin = tcx.sess.opts.test && !rustc_hir::find_attr!(tcx, crate, TestRunner(..));
        let mut descriptors: BTreeMap<String, Vec<LocalDefId>> = BTreeMap::new();
        let mut functions = Vec::new();
        if builtin {
            for id in tcx.hir_body_owners() {
                if matches!(tcx.def_kind(id), DefKind::Fn | DefKind::AssocFn) {
                    functions.push((
                        tcx.def_path_str(id.to_def_id()),
                        tcx.item_name(id.to_def_id()).to_string(),
                        id,
                    ));
                }
                if !matches!(tcx.def_kind(id), DefKind::Const { .. }) {
                    continue;
                }
                let Some(name) = rustc_hir::find_attr!(tcx, id, RustcTestMarker(name) => *name)
                else {
                    continue;
                };
                let ty = tcx.normalize_erasing_regions(
                    ty::TypingEnv::fully_monomorphized(),
                    tcx.type_of(id).instantiate_identity(),
                );
                // A test marker alone also occurs in custom test frameworks.
                // Require the descriptor generated by the built-in #[test].
                if let ty::Adt(def, _) = ty.kind() {
                    let module = tcx.parent(def.did());
                    // Pretty paths may use public reexports. Match the defining
                    // crate/module/item identities instead.
                    if tcx.crate_name(def.did().krate).as_str() == "test"
                        && tcx.item_name(def.did()).as_str() == "TestDescAndFn"
                        && tcx.item_name(module).as_str() == "types"
                        && tcx.parent(module).index == rustc_hir::def_id::CRATE_DEF_INDEX
                    {
                        descriptors.entry(name.to_string()).or_default().push(id);
                    }
                }
            }
        }
        Self {
            tcx,
            builtin,
            descriptors,
            functions,
        }
    }

    pub fn describe(&self, requested: &str) -> serde_json::Value {
        let unknown = |reason| {
            serde_json::json!({"status":"unclassified",
            "ordinary_test":false,"reason":reason})
        };
        if !self.builtin {
            return unknown("custom harness or compilation without the built-in test harness");
        }
        let matches: Vec<_> = self
            .functions
            .iter()
            .filter(|(full, short, _)| full == requested || short == requested)
            .collect();
        if matches.len() != 1 {
            return unknown("entry does not resolve to one function");
        }
        let (full, _, id) = matches[0];
        let Some(descriptors) = self.descriptors.get(full) else {
            return unknown("no matching built-in test descriptor");
        };
        if descriptors.len() != 1 {
            return unknown("ambiguous built-in test descriptors");
        }
        let ignored = rustc_hir::find_attr!(self.tcx, *id, Ignore { .. });
        let ignore_reason = rustc_hir::find_attr!(self.tcx, *id, Ignore { reason, .. } =>
            reason.map(|s| s.to_string()))
        .flatten();
        let should_panic = rustc_hir::find_attr!(self.tcx, *id, ShouldPanic { .. });
        let panic_message = rustc_hir::find_attr!(self.tcx, *id, ShouldPanic { reason } =>
            reason.map(|s| s.to_string()))
        .flatten();
        serde_json::json!({"status":"classified","harness":"libtest",
            "native_name":full,"function":full,
            "descriptor":self.tcx.def_path_str(descriptors[0].to_def_id()),
            "ignored":ignored,"ignore_reason":ignore_reason,
            "should_panic":should_panic,"panic_message":panic_message,
            "ordinary_test":!ignored && !should_panic})
    }
}
