//! Classify built-in test semantics from the checked compiler context.
use std::collections::BTreeMap;

use rustc_hir::def::DefKind;
use rustc_hir::def_id::LocalDefId;
use rustc_middle::ty::{self, TyCtxt};

pub struct Index<'tcx> {
    tcx: TyCtxt<'tcx>,
    builtin: bool,
    descriptors: BTreeMap<String, Vec<LocalDefId>>,
    functions: Vec<(String, String, LocalDefId)>,
}

impl<'tcx> Index<'tcx> {
    pub fn new(tcx: TyCtxt<'tcx>) -> Self {
        let builtin = tcx.sess.opts.test
            && !rustc_hir::find_attr!(tcx, crate, TestRunner(..));
        let mut descriptors: BTreeMap<String, Vec<LocalDefId>> = BTreeMap::new();
        let mut functions = Vec::new();
        if builtin {
            for id in tcx.hir_body_owners() {
                if matches!(tcx.def_kind(id), DefKind::Fn | DefKind::AssocFn) {
                    functions.push((tcx.def_path_str(id.to_def_id()),
                        tcx.item_name(id.to_def_id()).to_string(), id));
                }
                if !matches!(tcx.def_kind(id), DefKind::Const { .. }) { continue; }
                let Some(name) = rustc_hir::find_attr!(tcx, id, RustcTestMarker(name) => *name)
                    else { continue; };
                let ty = tcx.normalize_erasing_regions(ty::TypingEnv::fully_monomorphized(),
                    tcx.type_of(id).instantiate_identity());
                // A test marker alone also occurs in custom test frameworks.
                // Require the descriptor generated by the built-in #[test].
                if let ty::Adt(def, _) = ty.kind() {
                    let module = tcx.parent(def.did());
                    // Pretty paths may use public reexports. Match the defining
                    // crate/module/item identities instead.
                    if tcx.crate_name(def.did().krate).as_str() == "test"
                        && tcx.item_name(def.did()).as_str() == "TestDescAndFn"
                        && tcx.item_name(module).as_str() == "types"
                        && tcx.parent(module).index == rustc_hir::def_id::CRATE_DEF_INDEX {
                        descriptors.entry(name.to_string()).or_default().push(id);
                    }
                }
            }
        }
        Self { tcx, builtin, descriptors, functions }
    }

    pub fn list(&self) -> Result<serde_json::Value, String> {
        if !self.builtin {
            return Err("test discovery requires the built-in libtest harness".into());
        }
        if self.descriptors.len() > 16_384 {
            return Err("test discovery exceeds 16384 descriptors".into());
        }
        let mut tests = Vec::with_capacity(self.descriptors.len());
        for name in self.descriptors.keys() {
            if name.is_empty() || name.len() > 4096 {
                return Err("test name is outside the 1..4096 byte discovery bound".into());
            }
            let mut entry = self.describe(name);
            if entry["status"] != "classified" {
                return Err(format!("cannot classify built-in test {name:?}: {}", entry["reason"]));
            }
            entry["name"] = serde_json::json!(name);
            tests.push(entry);
        }
        Ok(serde_json::json!({"kind":"test-discovery","schema_version":1,
            "target":self.tcx.sess.opts.target_triple.to_string(),
            "strict_frontend":true,"executed":false,"harness":"libtest",
            "count":tests.len(),"tests":tests}))
    }

    pub fn describe(&self, requested: &str) -> serde_json::Value {
        let unknown = |reason| serde_json::json!({"status":"unclassified",
            "ordinary_test":false,"reason":reason});
        if !self.builtin {
            return unknown("custom harness or compilation without the built-in test harness");
        }
        let matches = crate::names::resolve(&self.functions, requested);
        if matches.len() != 1 { return unknown("entry does not resolve to one function"); }
        let id = matches[0];
        let full = self.tcx.def_path_str(id.to_def_id());
        let Some(descriptors) = self.descriptors.get(&full) else {
            return unknown("no matching built-in test descriptor");
        };
        if descriptors.len() != 1 { return unknown("ambiguous built-in test descriptors"); }
        let ignored = rustc_hir::find_attr!(self.tcx, id, Ignore { .. });
        let ignore_reason = rustc_hir::find_attr!(self.tcx, id, Ignore { reason, .. } =>
            reason.map(|s| s.to_string())).flatten();
        let should_panic = rustc_hir::find_attr!(self.tcx, id, ShouldPanic { .. });
        let panic_message = rustc_hir::find_attr!(self.tcx, id, ShouldPanic { reason } =>
            reason.map(|s| s.to_string())).flatten();
        serde_json::json!({"status":"classified","harness":"libtest",
            "native_name":full,"function":full,
            "descriptor":self.tcx.def_path_str(descriptors[0].to_def_id()),
            "ignored":ignored,"ignore_reason":ignore_reason,
            "should_panic":should_panic,"panic_message":panic_message,
            "ordinary_test":!ignored && !should_panic})
    }
}

#[derive(Clone, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct Filter {
    pub pattern: String,
    pub exact: bool,
}

impl Filter {
    pub fn parse(value: &str) -> Result<Self, String> {
        if value.len() > 32 * 1024 { return Err("test filter exceeds 32 KiB".into()); }
        let filter: Self = serde_json::from_str(value).map_err(|e| format!("invalid test filter: {e}"))?;
        if filter.pattern.len() > 4096 || filter.pattern.chars().any(|c| matches!(c, '\0' | '\r' | '\n')) {
            return Err("test filter must be at most 4096 bytes without NUL or line breaks".into());
        }
        Ok(filter)
    }

    /// Accept only a listing produced from this invocation's checked context.
    pub fn select(&self, mut listing: serde_json::Value) -> Result<(Vec<String>, serde_json::Value), String> {
        let tests = listing["tests"].as_array().ok_or("missing checked test list")?;
        let mut selected = Vec::new();
        let mut skipped = Vec::new();
        let mut unsupported = Vec::new();
        for test in tests {
            let name = test["name"].as_str().ok_or("missing checked test name")?;
            if !(if self.exact { name == self.pattern } else { name.contains(&self.pattern) }) { continue; }
            if test["ignored"] == true { skipped.push(name.to_owned()); }
            else if test["should_panic"] == true { unsupported.push(name.to_owned()); }
            else if test["ordinary_test"] == true { selected.push(name.to_owned()); }
            else { return Err(format!("unclassified test selected by filter: {name}")); }
        }
        if !unsupported.is_empty() {
            return Err(format!("test filter selects {} unsupported should_panic tests (first: {}); no tests executed",
                unsupported.len(), unsupported[0]));
        }
        if selected.is_empty() {
            return Err(format!("test filter selects no runnable tests ({} ignored matches); no tests executed", skipped.len()));
        }
        if selected.len() > 256 {
            return Err(format!("test filter selects {} runnable tests, exceeding the 256-entry limit; narrow the filter", selected.len()));
        }
        listing["kind"] = serde_json::json!("test-selection");
        listing["filter"] = serde_json::to_value(self).map_err(|e| e.to_string())?;
        listing["selected"] = serde_json::json!(selected);
        listing["skipped_ignored"] = serde_json::json!(skipped);
        Ok((selected, listing))
    }
}

#[cfg(test)]
mod filter_tests {
    use super::Filter;
    use serde_json::json;

    fn listing() -> serde_json::Value {
        json!({"tests":[
            {"name":"case", "ignored":false, "should_panic":false, "ordinary_test":true},
            {"name":"nested::case", "ignored":false, "should_panic":false, "ordinary_test":true},
            {"name":"nested::ignored", "ignored":true, "should_panic":true, "ordinary_test":false},
            {"name":"panic", "ignored":false, "should_panic":true, "ordinary_test":false}]})
    }
    #[test]
    fn filter_distinguishes_exact_and_substring_and_skips_ignored_panic() {
        let filter = Filter { pattern:"case".into(), exact:false };
        assert_eq!(filter.select(listing()).unwrap().0, ["case", "nested::case"]);
        let filter = Filter { pattern:"case".into(), exact:true };
        assert_eq!(filter.select(listing()).unwrap().0, ["case"]);
        let filter = Filter { pattern:"nested::".into(), exact:false };
        let (names, report) = filter.select(listing()).unwrap();
        assert_eq!(names, ["nested::case"]);
        assert_eq!(report["skipped_ignored"], json!(["nested::ignored"]));
    }
    #[test]
    fn filter_rejects_empty_unsupported_and_oversized_suites_before_execution() {
        for pattern in ["", "panic", "absent", "nested::ignored"] {
            assert!(Filter { pattern:pattern.into(), exact:false }.select(listing()).is_err());
        }
        let mut large = listing();
        large["tests"] = json!((0..257).map(|i| json!({"name":format!("case_{i}"),
            "ignored":false,"should_panic":false,"ordinary_test":true})).collect::<Vec<_>>());
        assert!(Filter { pattern:"case".into(), exact:false }.select(large).unwrap_err().contains("256-entry"));
    }
    #[test]
    fn filter_configuration_is_bounded_and_explicit() {
        assert!(Filter::parse(r#"{"pattern":"","exact":false}"#).is_ok());
        for value in ["{}", r#"{"pattern":"case","exact":1}"#, r#"{"pattern":"case","exact":false,"extra":0}"#,
                      r#"{"pattern":"line\n","exact":true}"#] {
            assert!(Filter::parse(value).is_err());
        }
        assert!(Filter::parse(&json!({"pattern":"x".repeat(4097),"exact":false}).to_string()).is_err());
    }
}
