//! Classify built-in test semantics from the checked compiler context.
use std::collections::BTreeMap;

use rustc_hir::def::DefKind;
use rustc_hir::def_id::LocalDefId;
use rustc_middle::ty::{self, TyCtxt};

pub struct Index<'tcx> {
    tcx: TyCtxt<'tcx>,
    builtin: bool,
    descriptors: BTreeMap<String, Vec<LocalDefId>>,
    functions: Vec<(String, String, LocalDefId)>,
}

impl<'tcx> Index<'tcx> {
    pub fn new(tcx: TyCtxt<'tcx>) -> Self {
        let builtin = tcx.sess.opts.test
            && !rustc_hir::find_attr!(tcx, crate, TestRunner(..));
        let mut descriptors: BTreeMap<String, Vec<LocalDefId>> = BTreeMap::new();
        let mut functions = Vec::new();
        if builtin {
            for id in tcx.hir_body_owners() {
                if matches!(tcx.def_kind(id), DefKind::Fn | DefKind::AssocFn) {
                    functions.push((tcx.def_path_str(id.to_def_id()),
                        tcx.item_name(id.to_def_id()).to_string(), id));
                }
                if !matches!(tcx.def_kind(id), DefKind::Const { .. }) { continue; }
                let Some(name) = rustc_hir::find_attr!(tcx, id, RustcTestMarker(name) => *name)
                    else { continue; };
                let ty = tcx.normalize_erasing_regions(ty::TypingEnv::fully_monomorphized(),
                    tcx.type_of(id).instantiate_identity());
                // A test marker alone also occurs in custom test frameworks.
                // Require the descriptor generated by the built-in #[test].
                if let ty::Adt(def, _) = ty.kind() {
                    let module = tcx.parent(def.did());
                    // Pretty paths may use public reexports. Match the defining
                    // crate/module/item identities instead.
                    if tcx.crate_name(def.did().krate).as_str() == "test"
                        && tcx.item_name(def.did()).as_str() == "TestDescAndFn"
                        && tcx.item_name(module).as_str() == "types"
                        && tcx.parent(module).index == rustc_hir::def_id::CRATE_DEF_INDEX {
                        descriptors.entry(name.to_string()).or_default().push(id);
                    }
                }
            }
        }
        Self { tcx, builtin, descriptors, functions }
    }

    pub fn list(&self) -> Result<serde_json::Value, String> {
        if !self.builtin {
            return Err("test discovery requires the built-in libtest harness".into());
        }
        if self.descriptors.len() > 16_384 {
            return Err("test discovery exceeds 16384 descriptors".into());
        }
        let mut tests = Vec::with_capacity(self.descriptors.len());
        for name in self.descriptors.keys() {
            if name.is_empty() || name.len() > 4096 {
                return Err("test name is outside the 1..4096 byte discovery bound".into());
            }
            let mut entry = self.describe(name);
            if entry["status"] != "classified" {
                return Err(format!("cannot classify built-in test {name:?}: {}", entry["reason"]));
            }
            entry["name"] = serde_json::json!(name);
            tests.push(entry);
        }
        Ok(serde_json::json!({"kind":"test-discovery","schema_version":1,
            "target":self.tcx.sess.opts.target_triple.to_string(),
            "strict_frontend":true,"executed":false,"harness":"libtest",
            "count":tests.len(),"tests":tests}))
    }

    pub fn describe(&self, requested: &str) -> serde_json::Value {
        let unknown = |reason| serde_json::json!({"status":"unclassified",
            "ordinary_test":false,"reason":reason});
        if !self.builtin {
            return unknown("custom harness or compilation without the built-in test harness");
        }
        let matches = crate::names::resolve(&self.functions, requested);
        if matches.len() != 1 { return unknown("entry does not resolve to one function"); }
        let id = matches[0];
        let full = self.tcx.def_path_str(id.to_def_id());
        let Some(descriptors) = self.descriptors.get(&full) else {
            return unknown("no matching built-in test descriptor");
        };
        if descriptors.len() != 1 { return unknown("ambiguous built-in test descriptors"); }
        let ignored = rustc_hir::find_attr!(self.tcx, id, Ignore { .. });
        let ignore_reason = rustc_hir::find_attr!(self.tcx, id, Ignore { reason, .. } =>
            reason.map(|s| s.to_string())).flatten();
        let should_panic = rustc_hir::find_attr!(self.tcx, id, ShouldPanic { .. });
        let panic_message = rustc_hir::find_attr!(self.tcx, id, ShouldPanic { reason } =>
            reason.map(|s| s.to_string())).flatten();
        serde_json::json!({"status":"classified","harness":"libtest",
            "native_name":full,"function":full,
            "descriptor":self.tcx.def_path_str(descriptors[0].to_def_id()),
            "ignored":ignored,"ignore_reason":ignore_reason,
            "should_panic":should_panic,"panic_message":panic_message,
            "ordinary_test":!ignored && !should_panic})
    }
}
