"""Concise current status from one manifest; historical detail stays in results."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def read(name):
    return json.loads((ROOT / name).read_text())


def render():
    config = read('benchmarks/current-status.json')
    integration = read(config['integration'])
    primary, held = read(config['primary']), read(config['heldout'])
    if (integration['tool_key'] != config['tool_key'] or
            not integration['component_identity_matches'] or
            not primary['primary_performance_gates_passed'] or not held['heldout_gates_passed']):
        raise RuntimeError('current retained evidence differs from manifest')
    cases = [(c['label'], c['run_id']) for c in primary['cases'] + held['cases']]
    lines = ['# Current measured status', '',
        f"Retained build **{config['source_commit'][:7]}/{config['tool_key'][:8]}**: custom interpreter and direct AArch64 JIT, strict rustc type/borrow checking. The exec Cargo wrapper is deployed.", '',
        'The retained measurements put folded near the specified native control and token about 2.3× slower. Other selected workflows save code-generation/link time while executing their original assertions. Native debuginfo/link settings are untuned; full libtest compatibility is unfinished.', '',
        'Times below come from each row’s own three-cycle, five-edit history. Native uses O0/incremental, 18 jobs/default test threads; custom uses four jobs. Cold means empty per-mode caches, excluding tool/sysroot bootstrap and OS cache coldness.', '',
        '| Workflow | Warm native | Warm custom | Cargo check | Custom/check | Cold native | Cold custom |',
        '| --- | ---: | ---: | ---: | ---: | ---: | ---: |']
    cold_losses = 0
    for label, run in cases:
        report = read(f'results/{run}/summary.json')
        if report['tool_builds']['candidate']['tool_key'] != config['tool_key']:
            raise RuntimeError('status row uses a different tool')
        warm, cold = report['median_seconds'], report['cold_success_seconds']
        check = report['check_floor']['median_seconds']
        cold_losses += cold['candidate'] > cold['native']
        lines.append(f"| [{label}](results/{run}/summary.json) | {warm['native']:.3f}s | {warm['candidate']:.3f}s | {check:.3f}s | {warm['candidate']/check:.2f}× | {cold['native']:.3f}s | {cold['candidate']:.3f}s |")
    lines += ['',
        f'Custom cold commands are slower on {cold_losses} of {len(cases)} rows. Cargo check executes no tests; custom/check is a descriptive overhead comparison, not a causal subtraction. Paired changes establish version comparisons; cross-session absolute medians do not.', '',
        'Retained qualification: 289 debug/release tests (one ignored), 47,004 broad validation commands, 245 TLS/destructor commands and 382 fre body passes (seven ignored). Seven held-out histories passed separate 5% wall/CPU regression guards. Private results expose aggregates only.', '',
        'The lightweight wrapper is in the retained build despite failing its standalone cold-performance gate. Budget-register, call-slot and whole-call candidates remain parked. A new 18-custom-worker latency preset is on the development branch; it does not alter the measurements above.', '']
    screen, decision = read(config['latest_screen']), read(config['latest_decision'])
    if screen['status'] != 'passed' or decision['status'] != 'parked' or screen['advance_to_full_comparison']:
        raise RuntimeError('latest scalar decision changed')
    lines += ['**Latest scalar ABI screen: parked.** Five real edits per case, original tests and wrong-edit controls; all correctness checks passed.', '',
        '| Workload | Paired wall change | Paired CPU change |', '| --- | ---: | ---: |']
    for case in screen['cases']:
        lines.append(f"| {case['label']} | {(case['wall_ratio']-1)*100:+.2f}% | {(case['cpu_ratio']-1)*100:+.2f}% |")
    lines += ['',
        'Token missed the 8% screening target. Execution saved about 170ms paired while Cargo added 144ms. Full scalar A/A and held-outs are stopped. Source lives under `crates/` on `experiment/scalar-value-abi` (measured commit `840fdb5`); the timing tool used the same wrapper on both sides.', '',
        '[Scalar assessment](results/scalar-edit-smoke-01/assessment.md).', '',
        '**Open adoption work:** tuned native controls; complete test-suite execution; unwinding, threads and general OS/FFI; deterministic/reusable export graphs. Selected test-body results are not whole-project qualification.', '',
        '**Next:** ' + config['next'], '',
        f"[Review decisions]({config['review']}) · [Work state](STATE.md) · [Evidence index](results/INDEX.md) · [Retention policy](results/RETENTION.md)", '',
        'Generated by `python3 scripts/update_status.py` from `benchmarks/current-status.json` and the linked receipts.', '']
    return '\n'.join(lines)
