#!/usr/bin/env python3
"""Generate current benchmark tables from the qualified aggregate and linked reports."""
import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CORPUS = 'results/local-memory-forwarding-01/summary.json'
REPEATED = 'results/paired-repeated-token-01/summary.json'
COMPUTE = {'folded-literal-trie', 'token-phrase', 'forward-anchored-tls', 'pgrust-sha1-inline8'}


def render():
    corpus = json.loads((ROOT / CORPUS).read_text())
    repeated = json.loads((ROOT / REPEATED).read_text())
    rows = corpus['workflows']
    for row in rows:
        data = (ROOT / row['report']).read_bytes()
        if hashlib.sha256(data).hexdigest() != row['report_sha256']:
            raise RuntimeError('corpus input hash changed: ' + row['report'])
    lines = [
        '# Measured status', '',
        'Generated by `python3 scripts/update_status.py`. These tables describe the',
        'last full nine-workflow performance qualification, not every later source',
        'change. See [CHANGELOG.md](CHANGELOG.md) for subsequent fixes.', '',
        f"Measured engine `{corpus['measured_tool_key'][:8]}`; retained source `{corpus['retained_tool_key'][:8]}`",
        '(local-memory forwarding, Git `6b2c61f`). The two source keys differ in a',
        'test-only correction; both production binaries are byte-identical. Native',
        'uses the repository test profile, four Cargo jobs and one test thread.',
        'It is an explicit control, not the fastest qualified native configuration.', '',
        'All numbers below are median complete commands after five different',
        'cumulative source edits on one shared Apple Silicon macOS host.',
        'They include launcher, compilation/export, linking where applicable,',
        'and selected test execution. Ratio is custom/native; lower is faster.', '',
    ]
    for heading, is_compute in [('Workflows with material guest execution', True), ('Workflows dominated by frontend/linking', False)]:
        lines += ['## ' + heading, '', '| Workflow | Native | Custom JIT | Ratio |', '| --- | ---: | ---: | ---: |']
        for row in rows:
            if (row['label'] in COMPUTE) != is_compute:
                continue
            n, c = row['medians']['native'], row['medians']['candidate']
            lines.append(f"| [{row['label']}]({row['report']}) | {n:.3f} s | {c:.3f} s | {c/n:.2f}× |")
        lines += ['']
    lines += [
        '## Repeated token edits', '',
        f"Three cycles, fifteen edited pairs: native {repeated['median_seconds']['native']:.3f} s,",
        f"previous JIT {repeated['median_seconds']['baseline']:.3f} s, retained JIT {repeated['median_seconds']['candidate']:.3f} s.",
        'Corresponding engines used identical bytecode, but revisiting the same',
        'source after the first cycle changed artifact layout. The failed stronger',
        'identity check is preserved. [Assessment](results/paired-repeated-token-01/assessment.md).', '',
        '## Coverage and limits', '',
        f"The performance-qualified build passed {corpus['bytecode_tests']} bytecode unit/integration tests",
        f"and {corpus['exporter_tests']} exporter tests. The library-only count is smaller.",
        'The native differential suite ran 23,502 cases with inlining off and the',
        'same 23,502 with it on; 245 TLS checks also passed.', '',
        'The fre replay selected 389 original bodies: 382 passed and 7 were ignored.',
        'This required `--allocation-limit 150000 --trap-unsupported-calls` and',
        '`--run-try-callbacks`, plus the recorded MIR/inlining settings. It invokes',
        'test bodies directly; it is not unfiltered libtest or whole-application',
        'coverage. Lowered audit entries are not counted as executed tests.', '',
        'No whole-codebase development workflow is qualified yet. Real unwinding,',
        'general OS/FFI use, threads and complete libtest semantics remain missing.',
        'Toolchain, fetched dependencies and std-MIR setup precede the reported',
        'cold Cargo commands. OS caches were not cleared.', '',
        '[All current evidence](results/INDEX.md) · [Protocol](BENCHMARKING.md) ·',
        '[Next work](RUNTIME-NEXT.md) · [Review decisions](docs/SUGGESTIONS-REVIEW-20260910.md)', '',
    ]
    entries = [dict(category='workflow', workflow=r['label'], report=r['report'],
        report_sha256=r['report_sha256'], measured_tool_key=corpus['measured_tool_key'],
        native_seconds=r['medians']['native'], custom_seconds=r['medians']['candidate']) for r in rows]
    for category, report in [
        ('corpus', CORPUS), ('repeated-workflow', REPEATED),
        ('diagnostic', 'results/retained-token-cpu-sample-04/summary.json'),
        ('diagnostic', 'results/frame-initialization-census-01/summary.json'),
        ('diagnostic', 'results/mir-frame-census-01/summary.json'),
        ('control-qualification', 'results/paired-native-controls-pgrust-02/summary.json'),
        ('control-qualification', 'results/e2e-native-controls-reference-01/summary.json'),
    ]:
        entries.append(dict(category=category, report=report,
            report_sha256=hashlib.sha256((ROOT / report).read_bytes()).hexdigest()))
    index = ['# Current evidence index', '',
        'Generated by `python3 scripts/update_status.py`; hashes are in [index.json](index.json).',
        'This selects the current evidence. Historical reports remain at their original',
        'paths; omission is not deletion, supersession, or proof of irrelevance.', '',
        '| Category | Report |', '| --- | --- |']
    for entry in entries:
        path = entry['report'].removeprefix('results/')
        index.append(f"| {entry['category']} | [{entry.get('workflow', path)}]({path}) |")
    index += ['', '[Measured status](../STATUS.md) · [Earlier native-cache results](../RESULTS.md)', '']
    return {'STATUS.md': '\n'.join(lines), 'results/INDEX.md': '\n'.join(index),
        'results/index.json': json.dumps(dict(schema_version=1, entries=entries), indent=2) + '\n'}


if __name__ == '__main__':
    for name, content in render().items():
        (ROOT / name).write_text(content)
