#!/usr/bin/env python3
"""Generate current benchmark tables from the qualified aggregate and linked reports."""
import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CORPUS = 'results/native-controls-corpus-01/summary.json'
PREVIOUS = 'results/local-memory-forwarding-01/summary.json'
REPEATED = 'results/paired-repeated-token-01/summary.json'
COMPUTE = {'folded-literal-trie', 'token-phrase', 'forward-anchored-tls', 'pgrust-sha1-inline8'}


def render():
    corpus = json.loads((ROOT / CORPUS).read_text())
    previous = json.loads((ROOT / PREVIOUS).read_text())
    repeated = json.loads((ROOT / REPEATED).read_text())
    rows = corpus['workflows']
    options = corpus['plan']['options']
    key = options['candidate_tool_key']
    builds = json.loads((ROOT / 'benchmarks/tool-builds.json').read_text())['builds']
    commit = next(b['commit'] for b in builds if b['tool_key'] == key)
    if len(rows) != len(corpus['plan']['cases']):
        raise RuntimeError('incomplete workflow corpus')
    verifications = []
    for row in rows:
        data = (ROOT / row['report']).read_bytes()
        if hashlib.sha256(data).hexdigest() != row['report_sha256']:
            raise RuntimeError('corpus input hash changed: ' + row['report'])
        verification = json.loads((ROOT / row['report']).with_name('verification.json').read_text())
        if not verification['measurement_controls_verified'] or not verification['paired_bytecode_identical']:
            raise RuntimeError('workflow controls failed: ' + row['report'])
        verifications.append(verification)
    total_commands = sum(v['commands'] + v['check_commands'] for v in verifications)
    check_commands = sum(v['check_commands'] for v in verifications)
    artifacts = sum(v['exact_artifact_hashes_verified'] for v in verifications)
    lines = [
        '# Measured status', '',
        'Generated by `python3 scripts/update_status.py` from the completed repeated',
        'native-control corpus. [Assessment](results/native-controls-corpus-01/assessment.md).', '',
        f"Current engine `{key[:8]}`, Git `{commit[:7]}`; paired baseline `{options['baseline_tool_key'][:8]}`.",
        'The current change fixes codegen-limit handling; these measurements do not',
        'establish a runtime improvement over that baseline. Native uses explicit',
        f"root O0/incremental settings, {options['native_jobs']} Cargo jobs and default test concurrency.",
        'Manifest package overrides remain in effect.',
        f"Custom builds use {options['jobs']} Cargo jobs and the per-workflow MIR/runtime settings in",
        '[the pinned corpus](benchmarks/workflow-corpus.json). Linker/backend tuning',
        'is still unqualified; this is not a fastest-native claim.', '',
        f"All numbers below are median complete commands after five different edits",
        f"repeated through {options['cycles']} cycles on one shared Apple Silicon macOS host.",
        'They include launcher, compilation/export, linking where applicable,',
        'and selected test execution. Ratio is custom/native; lower is faster.', '',
    ]
    for heading, is_compute in [('Workflows with material guest execution', True), ('Workflows dominated by frontend/linking', False)]:
        lines += ['## ' + heading, '', '| Workflow | Native | Custom JIT | Ratio | Check reference |', '| --- | ---: | ---: | ---: | ---: |']
        for row in rows:
            if (row['label'] in COMPUTE) != is_compute:
                continue
            n, c = row['medians']['native'], row['medians']['candidate']
            lines.append(f"| [{row['label']}]({row['report']}) | {n:.3f} s | {c:.3f} s | {c/n:.2f}× | {row['check_median_seconds']:.3f} s |")
        lines += ['']
    lines += [
        'The independent check command uses the native profile/flags/jobs and a',
        'separate cache. It checks the library test target without executing tests.',
        'Its wall time is a reference, not an additive component or causal floor.', '',
        '## Verification and variation', '',
        f"All {total_commands} commands completed, including {check_commands} independent checks.",
        f"Wrong production edits were rejected; {artifacts} artifacts were hash-verified and",
        'corresponding JIT versions received identical bytecode. Original assertions',
        'and test sources were preserved. Child CPU, per-edit spreads, cold commands',
        'and source-reverting cycle anchors are retained in each linked report.', '',
        'Identical source after the first edit cycle can produce a different artifact',
        'layout. This occurred in all three fre workflows here. Cross-history semantic',
        'equivalence and the cause of the layout differences remain unresolved.',
        'All samples, including the slow token sample, remain in the reports.', '',
        '## Earlier repeated token comparison', '',
        f"Three cycles, fifteen edited pairs: native {repeated['median_seconds']['native']:.3f} s,",
        f"previous JIT {repeated['median_seconds']['baseline']:.3f} s, retained JIT {repeated['median_seconds']['candidate']:.3f} s.",
        'Corresponding engines used identical bytecode, but revisiting the same',
        'source after the first cycle changed artifact layout. The failed stronger',
        'identity check is preserved. [Assessment](results/paired-repeated-token-01/assessment.md).', '',
        '## Coverage and limits', '',
        'The current source passed 188 bytecode unit/integration, 11 exporter and',
        '3 historical-cache tests. [Test receipt](results/review-codegen-limits-01/summary.json).',
        f"The earlier `{previous['retained_tool_key'][:8]}` qualification ran 23,502 native differential",
        'cases with inlining off and the same 23,502 with it on; 245 TLS checks passed.',
        'Those broader suites have not been rerun on the current codegen-limit fix.', '',
        'That earlier fre replay selected 389 original bodies: 382 passed and 7 were ignored.',
        'This required `--allocation-limit 150000 --trap-unsupported-calls` and',
        '`--run-try-callbacks`, plus the recorded MIR/inlining settings. It invokes',
        'test bodies directly; it is not unfiltered libtest or whole-application',
        'coverage. Lowered audit entries are not counted as executed tests.', '',
        'No whole-codebase development workflow is qualified yet. Real unwinding,',
        'general OS/FFI use, threads and complete libtest semantics remain missing.',
        'Toolchain, fetched dependencies and std-MIR setup precede the reported',
        'cold Cargo commands. OS caches were not cleared.', '',
        '[All current evidence](results/INDEX.md) · [Protocol](BENCHMARKING.md) ·',
        '[Next work](RUNTIME-NEXT.md) · [Review decisions](docs/SUGGESTIONS-REVIEW-20260910.md)', '',
    ]
    entries = [dict(category='workflow', workflow=r['label'], report=r['report'],
        report_sha256=r['report_sha256'], measured_tool_key=key,
        native_seconds=r['medians']['native'], custom_seconds=r['medians']['candidate']) for r in rows]
    for category, report in [
        ('corpus', CORPUS), ('previous-corpus', PREVIOUS), ('repeated-workflow', REPEATED),
        ('source-qualification', 'results/review-codegen-limits-01/summary.json'),
        ('diagnostic', 'results/retained-token-cpu-sample-04/summary.json'),
        ('diagnostic', 'results/frame-initialization-census-01/summary.json'),
        ('diagnostic', 'results/mir-frame-census-01/summary.json'),
        ('diagnostic', 'results/native-call-census-01/summary.json'),
        ('diagnostic', 'results/native-call-census-02/summary.json'),
        ('control-qualification', 'results/paired-native-controls-pgrust-02/summary.json'),
        ('control-qualification', 'results/e2e-native-controls-reference-01/summary.json'),
    ]:
        entries.append(dict(category=category, report=report,
            report_sha256=hashlib.sha256((ROOT / report).read_bytes()).hexdigest()))
    index = ['# Current evidence index', '',
        'Generated by `python3 scripts/update_status.py`; hashes are in [index.json](index.json).',
        'This selects the current evidence. Historical reports remain at their original',
        'paths; omission is not deletion, supersession, or proof of irrelevance.', '',
        '| Category | Report |', '| --- | --- |']
    for entry in entries:
        path = entry['report'].removeprefix('results/')
        index.append(f"| {entry['category']} | [{entry.get('workflow', path)}]({path}) |")
    index += ['', '[Measured status](../STATUS.md) · [Earlier native-cache results](../RESULTS.md)', '']
    return {'STATUS.md': '\n'.join(lines), 'results/INDEX.md': '\n'.join(index),
        'results/index.json': json.dumps(dict(schema_version=1, entries=entries), indent=2) + '\n'}


if __name__ == '__main__':
    for name, content in render().items():
        (ROOT / name).write_text(content)
